force-app/main/default/objects/BournePlugins__c/BournePlugins__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Apex extensibility for the JSON Bourne package</description>
    <label>JSON Bourne Plugins</label>
</CustomObject>

force-app/main/default/objects/BournePlugins__c/fields/API_Post_Processor__c.field-meta.xml
<CustomField>
    <fullName>API_Post_Processor__c</fullName>
    <description>This Post Processor will run within all Apex Rest APIs in the package after any logic is executed, giving you the opportunity to turn anything back on like triggers/validation rules etc</description>
    <inlineHelpText>This Post Processor will run within all Apex Rest APIs in the package after any logic is executed, giving you the opportunity to turn anything back on like triggers/validation rules etc</inlineHelpText>
    <label>API Post Processor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BournePlugins__c/fields/API_Pre_Processor__c.field-meta.xml
<CustomField>
    <fullName>API_Pre_Processor__c</fullName>
    <description>This Pre Processor will run within all Apex Rest APIs in the package before any logic is executed, giving you the opportunity to turn anything off like triggers/validation rules etc</description>
    <inlineHelpText>This Pre Processor will run within all Apex Rest APIs in the package before any logic is executed, giving you the opportunity to turn anything off like triggers/validation rules etc</inlineHelpText>
    <label>API Pre Processor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Plugins.cls
global class Plugins {
  // Pre Processor
  public static Plugins.PreProcessor getInstancePreProcessor() {
    Object result = getInstance('API_Pre_Processor__c');
    return (Plugins.PreProcessor) (result == null
      ? new DefaultPreProcessor()
      : result);
  }

  global interface PreProcessor {
    void execute();
  }

  global class DefaultPreProcessor implements defaultInterface, PreProcessor {
    global void execute() {
    }
  }

  // Post Processor
  public static Plugins.PostProcessor getInstancePostProcessor() {
    Object result = getInstance('API_Post_Processor__c');
    return (Plugins.PostProcessor) (result == null
      ? new DefaultPostProcessor()
      : result);
  }

  global interface PostProcessor {
    void execute();
  }

  global class DefaultPostProcessor implements defaultInterface, PostProcessor {
    global void execute() {
    }
  }

  // Marker Interface
  public interface defaultInterface {
  }

  // Exception class
  class PluginException extends Exception {
  }

  // Method to instantiate class from custom setting field
  static Object getInstance(String pluginField) {
    BournePlugins__c pluginSettings = BournePlugins__c.getInstance();
    if (pluginSettings == null || pluginSettings.get(pluginField) == null)
      return null;

    Type t = Type.forName(null, (String) pluginSettings.get(pluginField));
    if (t == null)
      throw new PluginException(
        'No class called ' +
        pluginSettings.get(pluginField) +
        'found.'
      );
    return t.newInstance();
  }
}